const SET_EFFECT_LOADING = '@@app-reducer/SET_EFFECT_LOADING'
const CLEAR_EFFECT_LOADING = '@@app-reducer/CLEAR_EFFECT_LOADING'
const SIDEBAR_STATE = '@@app-reducer/SIDEBAR_STATE'
const SET_USERNAME_TO_STORE = '@@app-reducer/SET_USERNAME_TO_STORE'
const SET_RESET_APP_STORE = '@@app-reducer/SET_RESET_APP_STORE'
const PROFILE_LANGUAGE = '@@app-reducer/PROFILE_LANGUAGE'

export const ActionTypes = {
  SET_EFFECT_LOADING,
  CLEAR_EFFECT_LOADING,
  SIDEBAR_STATE,
  SET_USERNAME_TO_STORE,
  SET_RESET_APP_STORE,
  PROFILE_LANGUAGE
}
