export const EFFECT_LOADING = {
  LOGIN_PAGE: 'LOGIN_PAGE',
  CHECK_AUTH: 'CHECK_AUTH',
  GET_CITIES: 'GET_CITIES',
  TRIP_SEARCH: 'TRIP_SEARCH',
  CREATE_RESERVATION: 'CREATE_RESERVATION',
  GET_BOOKINGS: 'GET_BOOKINGS',
  GET_TICKET: 'GET_TICKET',
  GET_TRIPS: 'GET_TRIPS'
}
