export const FILTER_PROPERTIES_NAMES = {
  DEPARTURE: 'departure',
  ARRIVAL: 'arrival',
  DEPARTURE_COUNTRY: 'departureCountry',
  ARRIVAL_COUNTRY: 'arrivalCountry',
  CREATED_AT: 'createdAt',
  DEPARTURE_DATE: 'departureDate',
  RETURNT_DEPARTURE_DATE: 'returnDepartureDate',
  STATUS: 'status',
  PASSENGER_TRIP: 'passengerTrip',
  PASSENGER_DEPARTURE_DATE: 'passengerDepartureDate',
  LOCATION_COUNTRY: 'locationCountry',
  LOCATION_CITY: 'locationCity',
  AGENCIES_NAME: 'agenciesName',
  AGENCIES_GROUP: 'agenciesGroup',
  USERS_ROLE: 'usersRole',
  USERS_GROUP: 'usersGroup',
  USERS_ACCESS: 'usersAccess',
  DISCOUNTS_TYPE: 'discountsType',
  BAGGAGE_TYPE: 'baggageType',
  CARRIER_NAME: 'carrierName',
  ACTIVE: 'active'
}
