const apiBase = import.meta.env.VITE_SERVER_API

/* SERVICES */
const AUTH_SERVICE = `${apiBase}/auth`
const LOCATIONS_SERVICE = `${apiBase}/locations`
const DIRECTIONS_SERVICE = `${apiBase}/directions`
const BOOKINGS_SERVICE = `${apiBase}/bookings`
const TRIPS_SERVICE = `${apiBase}/trips`
const AGENCIES_SERVICE = `${apiBase}/agencies`
const USERS_SERVICE = `${apiBase}/users`
const CARRIERS_SERVICE = `${apiBase}/carriers`

/* AUTH SERVICE */
const LOGIN = `${AUTH_SERVICE}/login`
const VALIDATE_TOKEN = `${AUTH_SERVICE}/current`

/* LOCATIONS SERVICE */
const GET_LOCATIONS = `${LOCATIONS_SERVICE}`
const GET_CITIES = `${LOCATIONS_SERVICE}/cities`

/* DIRECTIONS SERVICE */
const TRIP_SEARCH = `${DIRECTIONS_SERVICE}/search`
const TRIP_SEARCH_NOT_AUTH = `${DIRECTIONS_SERVICE}/search/welcome`
const TRIP_SEARCH_FOR_REVERSE = `${DIRECTIONS_SERVICE}/search/trip/welcome`

/* BOOKINGS SERVICE */
const GET_BOOKINGS = `${BOOKINGS_SERVICE}`
const GET_BOOKINGS_ARCHIVED = `${BOOKINGS_SERVICE}/archived`
const GET_TICKET = `${BOOKINGS_SERVICE}/:id`
const CREATE_RESERVATION = `${BOOKINGS_SERVICE}/new`
const CREATE_RESERVATION_NOT_AUTH = `${BOOKINGS_SERVICE}/new/welcome`
const GET_PASSENGERS = `${BOOKINGS_SERVICE}/passengers`
const GET_ALL_PASSENGERS = `${BOOKINGS_SERVICE}/passengers/all`

/* TRIPS SERVICE */
const GET_TRIPS = `${TRIPS_SERVICE}`

/* AGENCIES SERVICE */
const GET_AGENCIES = `${AGENCIES_SERVICE}`
const CREATE_AGENCY = `${AGENCIES_SERVICE}/new`
const CHANGE_AGENCY = `${AGENCIES_SERVICE}/:id`
const DELETE_AGENCY = `${AGENCIES_SERVICE}/delete`

/* USERS SERVICE */
const GET_USERS = `${USERS_SERVICE}`
const GET_CONSOLIDATORS = `${USERS_SERVICE}/consolidators`

/* CARRIERS SERVICE */
const GET_CARRIERS = `${CARRIERS_SERVICE}`

export const URL = {
  LOGIN,
  VALIDATE_TOKEN,
  GET_CITIES,
  TRIP_SEARCH,
  TRIP_SEARCH_NOT_AUTH,
  CREATE_RESERVATION,
  CREATE_RESERVATION_NOT_AUTH,
  TRIP_SEARCH_FOR_REVERSE,
  GET_BOOKINGS,
  GET_BOOKINGS_ARCHIVED,
  GET_TICKET,
  GET_TRIPS,
  GET_PASSENGERS,
  GET_LOCATIONS,
  GET_ALL_PASSENGERS,
  GET_AGENCIES,
  CREATE_AGENCY,
  CHANGE_AGENCY,
  DELETE_AGENCY,
  GET_USERS,
  GET_CONSOLIDATORS,
  GET_CARRIERS
}
